### Builder
FROM rust:1.81.0-bookworm as builder
WORKDIR build
COPY ./.cargo ./.cargo
COPY ./src ./src
COPY ./Cargo.toml ./
COPY ./Cargo.lock ./
RUN cargo build --release

### Runner
FROM gcr.io/distroless/cc-debian12 as runner
COPY --from=builder /build/target/release/graphql-rust /opt/server
ENTRYPOINT ["/opt/server"]
